### ISSUE TITLE
HTML Sanitisation

### ISSUE THREAD

**Issue by braaandon** [techienickb/hap#7]
Anyone with permissions to create an announcement can write any Javascript code in the announcement edit prompt and it will be served to anyone visiting the website. User cookies are protected by the HttpOnly header, so it can't steal those. However, it can still inject itself into things like the Reset Password section and/or redirect the user to something else malicious.

Demonstration:
 
![image](https://user-images.githubusercontent.com/86573128/142762349-cb9b025c-cb8c-4fe2-b06a-66a7b6f0053e.png)

Offending code:

```cs
  [WebInvoke(UriTemplate = "Save", ResponseFormat=WebMessageFormat.Json, Method = "POST", BodyStyle = WebMessageBodyStyle.WrappedRequest)]
  public bool Save(string content, bool show)
  {
      XmlDocument doc = new XmlDocument();
      doc.Load(HttpContext.Current.Server.MapPath("~/App_Data/Announcement.xml"));
      XmlNode node = doc.SelectSingleNode("/announcement");
      node.Attributes[0].Value = show.ToString();
      node.InnerXml = string.Format("<![CDATA[ {0} ]]>", HttpUtility.UrlDecode(content, System.Text.Encoding.Default));
      doc.Save(HttpContext.Current.Server.MapPath("~/App_Data/Announcement.xml"));
      return true;
  }
```

**Comment by techienickb** [comment]
This project isn't active anymore, and hasn't been since 2012.  Source code is provided as is.  I strongly recommend running HAP+ via an AAD App Proxy using constrained kerberos which disables the password reset functionality.

Feel free to do a PR with a possible fix but the original code base is very old now.
